### ISSUE TITLE
"flex is not defined" with 2.4.1+ 

### ISSUE THREAD

**Issue by simakwm** [zeit/next.js#2149]
I'm using global stylesheet and sass.

With 2.4.1 or beta8, my app doesn't build anymore. Fails with:

Module build failed: ReferenceError: /path/to/my/app/styles/index.scss: flex is not defined

**Comment by davemcorwin** [comment]
I have the same issue, it started in v3 beta7 and looks like it has something to do with stylis. In my case, I have external scss that I am bringing by following [the global css example](https://github.com/zeit/next.js/tree/v3-beta/examples/with-global-stylesheet.)

It looks like stylis is attempting to handle this but it is already handled.

**Comment by jaydenseric** [comment]
This is likely fixed in Stylis, see https://github.com/thysultan/stylis.js/blob/master/CHANGELOG.md#3015-june-02-2016. [Dont mind the incorrect year of the changelog entry](https://github.com/thysultan/stylis.js/issues/31).

**Comment by simakwm** [comment]
> This is likely fixed in Stylis, see https://github.com/thysultan/stylis.js/blob/master/CHANGELOG.md#3015-june-02-2016.

Confirmed! Thanks.

**Comment by ChennyBaBy** [comment]
Sorry for the late question, how did you get round this issue with Stylis? I tried doing `npm update stylis` but it's still not working.

**Comment by simakwm** [comment]
Update next like "yarn add next@2.4.1" or "npm install --save next@2.4.1

**Comment by ChennyBaBy** [comment]
I ended up doing a shrinkwrap with the stylis version pinned to the latest.

**Comment by TheCrow1213** [comment]
Not sure if this is an issue for anyone else, but I'm having the error w/ any version past 2.3.1 :/

**Comment by bubuzzz** [comment]
I am using next 2.4.3. With the example with-global-styles, then it works fine. However, when I add less support, it stars to give this error again

**Comment by bubuzzz** [comment]
Just saw that the latest 2.4.4 come with the stylis 3.1.5. I don't have the problem anymore. Awesome !!!!
