### ISSUE TITLE
Pretty Static Export Paths

### ISSUE THREAD

**Issue by kennedyrose** [zeit/next.js#2944]
Is there any way to trim the `/` off of the static export output? Many static hosts like GH pages and Netlify support trimming the `.html` off of your paths for "pretty" URL paths.

But it looks like static export turns all of your `/path/links` to `/path/links/`. It'd be nice if there was an option to turn on pretty URL paths for exporting to the static hosts that support them.

**Comment by MAPESO** [comment]
Can not be omitted **"/"**.  Could you give me an example of what you are saying about the routes.

**Comment by kennedyrose** [comment]
So basically, in my `next.config.js` file, I've got a route specified as `/path/product`. Whenever I export, the path becomes `/path/product/`.

But most static hosts actually do support the `/path/product` link without the trailing slash. So I was wondering if it'd be possible to provide a CLI option to `next export` that would not rewrite the URLs to have trailing slashes.

**Comment by pruhstal** [comment]
@kennedyrose sounds like a job for custom routes:

https://github.com/zeit/next.js/blob/master/examples/with-next-routes/routes.js

Although if you're already doing that, then express has an optional param you can pass in called `strict` for strict routing.

![screen shot 2017-09-22 at 11 35 10 pm](https://user-images.githubusercontent.com/624807/30770814-bcc86c78-9fee-11e7-8467-018e366c566a.png)

Maybe that'll do it?

**Comment by timneutkens** [comment]
@pruhstal @kennedyrose There's a wiki article for that:tm: https://github.com/zeit/next.js/wiki/Centralizing-Routing

**Comment by NathanielHill** [comment]
This is solved :tada:
https://zeit.co/blog/new-static-deployments

**Comment by mrcoles** [comment]
It is only solved for `now` deployments. It’s not solved for general exports.

**Comment by Soundvessel** [comment]
Confirmed this is still an issue running an export from Next v8.0.3. Even when I type `/queue`  without the trailing slash in the address bar the resulting page adds it back in even though my export settings omit the trailing slashes.

Here are my `exportPathMap` settings:
```
    return {
      '/'      : { page: '/system' },
      '/queue' : { page: '/queue' },
      '/tunnel': { page: '/tunnel' },
      '/lanes' : { page: '/lanes' },
    }
```

**Comment by NathanielHill** [comment]
@mrcoles Seems you are right. Hopefully this can be addressed someday :man_shrugging:
