### ISSUE TITLE
Absolute paths used for `_error.js` and `_document.js` webpack entries

### ISSUE THREAD

**Issue by vjpr** [zeit/next.js#3785]
In `server/build/webpack/utils.js`, `nextPagesDir` is absolute and is used to add `_error.js` and `_document.js` as webpack entries.

This absolute path prevents you from compiling the code in one dir, and then moving it to another dir. All paths need to be relative.

https://github.com/zeit/next.js/blob/e093441bad588e98765a05df90f76f75283eda07/server/build/webpack/utils.js#L4

I am using pnpm, this could also be related...

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |  5.0.0       |
| node    |   8.1.2      |
| OS      |   macOS + Ubuntu      |
| browser |         |
| etc     |         |

**Comment by timneutkens** [comment]
Already fixed in next@canary.

**Comment by vjpr** [comment]
@timneutkens I'm still seeing an absolute `next` alias in the webpack config.

https://github.com/zeit/next.js/blob/efe9afb2be3059f97ac06b8fe105d8d9e30368a5/server/build/webpack.js#L151

**Comment by timneutkens** [comment]
Doesn't matter. It'll not compile to absolute paths. It'll compile to webpack requires.
