### ISSUE TITLE
Dev Server Navigation broken

### ISSUE THREAD

**Issue by stramel** [zeit/next.js#4324]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior

Navigating to another _non-built_ page should navigate after page has built successfully.

## Current Behavior

Navigating to another _non-built_ page reloads the page after intended page has built successfully. Clicking to navigate again after the intended page has been built, correctly routes to the page.

## Context

Just more of a pain in development because we aren't sure that it isn't happening in a production build without double checking every time.

I am running a custom express server with custom document and app.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    v6     |
| node    |    v9.11.1     |
| OS      |    Windows 10     |
| browser |    Chrome 66     |
| etc     |         |

**Comment by timneutkens** [comment]
Please provide a clear way to reproduce, essiest way for us go check it out is a repository.

**Comment by rosenbergdev** [comment]
I've had similar issue. I was trying to modify `config.entry` in `next.config.js` ...

When I tried to navigate to non-built page I got `[HMR] The following modules couldn't be hot updated: (Full reload needed)...`

Problem was with my custom webpack configuration. I was appending Service worker registration file like this:

	const oldEntry = config.entry
	
	config.entry = () =>
    oldEntry().then(entry => {
      entry['main.js'].push(path.resolve('./utils/sw-install'))
      return entry
  
After I wrapped it inside `if(!dev)...` HMR started to work again.

**Comment by makstr** [comment]
After upgrading to Next 6 / babel 7 I am also seeing some inconsistency in page rendering and getting (full reload needed). It applies to routes that have not been been previously built, so pretty close to what @stramel described

**Comment by stramel** [comment]
@timneutkens I haven't been able to reproduce it yet. However I have tracked down that it seems while the page is building, HMR sends a message saying the `_app` file has changed and is causing it to reload the current page.

Any thoughts?

**Comment by stramel** [comment]
@tlenclos I appreciate your input on this issue. I still haven't found a way to fix this issue across the board. I did manage to bandaid one page by moving selectors from an external file into the same file as the page. However this didn't work across the board.

When the selectors were in another file, HMR reported about 30 files changed including `_app.js`. (No actual files were changed, just clicked a link for navigation on the localhost)

When the selectors were in the same file as the page, HMR reported no file changes/updates and properly routed. 

@timneutkens I have been unable to reproduce this scenario in a repo yet but it does seem that HMR is firing false positives on file changes. It seems very arbitrary but I'm sure there is a central issue. I will continue to keep digging.

**Comment by stramel** [comment]
Update: I pulled out the `_app.js` file and it seemed to fix the HMR issue. I'm working to reproduce this.

**Comment by yves-s** [comment]
I already postet my issue here: #2060
In my case it seems to be a Problem with polyfill. As I remove the polyfill settings the navigation works as expected but I can't use the app properly on IE11 because of missing functionality.

**Comment by stramel** [comment]
@yves-s @makstr This doesn't appear related to #2060. This is happening on the latest Chrome and seems directly tied to the HMR. I have also checked my next.config.js for outdated config.

**Comment by Everettss** [comment]
@stramel I probably faced the same problem. Try to downgrade `react-hot-loader` to version "4.0.0" - it fixes problem for me.

**Comment by Everettss** [comment]
@stramel Oh it's not a temporary solution - only for debugging purposes:
```
npm i react-hot-loader@4.0.1 --save-exact
```

and then remove dir:

```
node_modules/next/node_modules/react-hot-loader
```

Doing so helped me with finding that problem you mention is related to version `react-hot-loader` 4.1.0 and above.

**Comment by stramel** [comment]
Appears that #4388 may have fixed part of the issue with my setup.

Now I am getting:
![image](https://user-images.githubusercontent.com/855184/40090954-9eb7ac36-587a-11e8-9ff7-f4b1b5b90578.png)

with this as my `dist` folder:
![image](https://user-images.githubusercontent.com/855184/40090968-af927824-587a-11e8-8eeb-0053790d1e20.png)

**Comment by stramel** [comment]
The `undefined` chunk is a problem with `dynamic(import('path/to/module'))`

I disabled that in hopes that it might work or be able to debug further...

The routing is `/_document` even though I am trying to route to `/network/:networkId`
![image](https://user-images.githubusercontent.com/855184/40098684-600c10e4-58a2-11e8-9938-0306aa75fc63.png)

**Comment by stramel** [comment]
Seems that the `hot-reloader.js` is properly detecting that I want to route to `/networks` however the client `webpack-hot-middleware-client.js` is detecting a change in `/_document`?

![image](https://user-images.githubusercontent.com/855184/40100159-990067aa-58a8-11e8-9a94-8c8a95c72eb4.png)

**Comment by stramel** [comment]
Tried downgrading to `styled-components#^2.1.0` as the example uses but it is still causing a reload...

When I remove the `styled-components` it works. Will see if I can reproduce now.

**Comment by timneutkens** [comment]
@stramel can you try latest canary? I applied a fix for something similar to your issue yesterday.

**Comment by timneutkens** [comment]
@stramel interesting that it says `/_document` is updated too 🤔 Let me add a check for that too.

**Comment by stramel** [comment]
@timneutkens That did the trick!!! 🎉 🎉 🎉  Fixed with `6.0.3-canary.0`. I appreciate you taking a look at my debugging notes and figuring out the issue!

**Comment by timneutkens** [comment]
Thanks for the extensive debugging from your side 😌 It wasn't the easiest issue to find :+1:

**Comment by madhums** [comment]
@timneutkens I am still facing this issue with next@6.0.3 I put up a repo here https://github.com/madhums/nextapp-hotreload-issue

**Comment by timneutkens** [comment]
@madhums expecting your issue will be fixed by https://github.com/zeit/next.js/pull/4497, @alexindigo made a minimal example in which it still failed.

**Comment by madhums** [comment]
@timneutkens I confirm it fixes the issue! Thanks! Good job!

**Comment by timneutkens** [comment]
Great @madhums!

**Comment by madhums** [comment]
Hi Tim, I still face this issue. Not really sure what the problem is! Tried `6.0.4-canary.3` also. I trying to make a repo which can reproduce.
