### ISSUE TITLE
Module not found: Error: Cannot resolve module 'next/router'

### ISSUE THREAD

**Issue by smallseven1213** [zeit/next.js#472]
Hi

I try to use next/router in my project.
but always show "Module not found: Error: Cannot resolve module 'next/router'"

try to reinstall nextjs, but next/router is always missing.

**Comment by arunoda** [comment]
May be it's related to this: https://github.com/zeit/next.js/pull/464
@nkzawa shall we cut a new beta?

**Comment by rauchg** [comment]
+1 @arunoda @nkzawa

**Comment by mikkokut** [comment]
+1

**Comment by rauchg** [comment]
+1

**Comment by rauchg** [comment]
😂

**Comment by souporserious** [comment]
+1

**Comment by arunoda** [comment]
Guys, we've fixed this problem and now it's available on NPM.
But we fixed an another related issue.

@rauchg @nkzawa could you cut a new beta release again?

**Comment by nkzawa** [comment]
Released `2.0.0-beta.2`.

**Comment by souporserious** [comment]
Still getting an error when trying to use the router :/ any ideas?

![image](https://cloud.githubusercontent.com/assets/2762082/21468662/7e069344-c9d3-11e6-876a-187da5e6aea7.png)

**Comment by arunoda** [comment]
@souporserious You may need to do `yarn upgrade`

**Comment by souporserious** [comment]
I'm dumb 😞 thanks! That worked perfect 😄
