### ISSUE TITLE
[with-apollo-auth] - All component in a page are re-constructed when route query params changed

### ISSUE THREAD

**Issue by tsupol** [zeit/next.js#4775]
# Example: with-apollo-auth

## Example name
With Apollo Auth

## Describe the bug
Every components in the page are being reconstructed again (constructor() is called) destroying existing states which is not a normal behavior of Next.js.
**Other with-apollo examples work just fine.**
**The older version of with-apollo-auth works fine too.**

## To Reproduce
1. Add a test component `/component/TestRefresh.js`
```
import React from 'react'

export default class TestRefresh extends React.PureComponent {

  constructor(props) {
    super(props)
    console.log('[constructor called]');
  }

  render () {
    const { message } = this.props
    return (
      <div>
        <h1>Test Page</h1>
        <h2>{message}</h2>
      </div>
    )
  }
}
```
2. Add a test page `/pages/test.js` with the test component in it
```
import React from 'react'
import TestRefresh from '../components/TestRefresh'
import Link from 'next/link'
export default class Test extends React.PureComponent {

  static getInitialProps({ query }) {
    return { query }
  }

  render() {
    return (
      <React.Fragment>
        <TestRefresh message={this.props.query.message} />
        <ul>
          <li><Link href={{ pathname: '/test', query: { message: "filter1" } }}>
            <a>filter1</a>
          </Link></li>
          <li><Link href={{ pathname: '/test', query: { message: "filter2" } }}>
            <a>filter2</a>
          </Link></li>
        </ul>
      </React.Fragment>
    )
  }
}
```
3. Run the test page and click on the link
4. You will see in the console that the constructor are called every time you click on the link 

## Expected behavior
The page should not refresh when route query param changed.

## Screenshots
<img width="1099" alt="screen shot 2561-07-13 at 15 59 57" src="https://user-images.githubusercontent.com/6997714/42683200-d64cd10c-86b6-11e8-94cd-b48bfca5fbf3.png">
You will see [constructor called] in the console every time you click on the link (filter1, filter2)

## System information
 - OS: both
 - Version of Next.js: [e.g. 6.1.1]

## Additional context
Using routing params to trigger changes in a page is important and widely used.
The page refresh will destroy all the current states thus making change by routing params is impossible.

**Comment by wstam88** [comment]
Same here

**Comment by keeth** [comment]
This example [calls getDataFromTree() on the client as well as the server](https://github.com/zeit/next.js/commit/915673fcd69e120084c14582fd80f2fc7140c147#r30408000), which is probably why you are seeing extra constructor calls.

**Comment by timneutkens** [comment]
This is no longer the case, so this is fixed.

**Comment by keeth** [comment]
@timneutkens i still see it in master.. only in with-apollo-auth, not in with-apollo.

https://github.com/zeit/next.js/blob/master/examples/with-apollo-auth/lib/withApollo.js#L46

**Comment by timneutkens** [comment]
Ah my bad, with-apollo-auth should be updated to be like with-apollo 👍

Feel free to implement this 🙏
