### ISSUE TITLE
when jumping among pages, styles lost

### ISSUE THREAD

**Issue by wslx520** [zeit/next.js#4833]
# Bug report

## Describe the bug

I found this bug in `with-ant-design` example. but I think it's not a bug of example, it's a bug of next.js.

In this example, there is only one page, so it works fine. but, when built one more page, and jump between pages, you can find styles lost.

## To Reproduce

1. run the `with-ant-design` example properly (by `npm run dev`). It looks good:
![image](https://user-images.githubusercontent.com/1026909/43182052-6fba4b44-9012-11e8-8752-5c3308be7054.png)

2. build one more page (named: `other`), and create a link between them. here is `other.js` source:

```javascript
import Layout from '../index.js'
import Link from 'next/link'
import { Select, Button } from 'antd'
const Option = Select.Option
export default () => (
    <Layout>
        <div style={{ marginTop: 100 }}>
            <Link href="/"><Button>Back to main</Button></Link>
            <Select>
                <Option value={null}>请选择</Option>
            </Select>
        </div>
    </Layout>
)
```
nothing special

3. at main page, click the link to `other`, and then, click the `Back to main` to go back. then you can see the styles are not corrent:

![image](https://user-images.githubusercontent.com/1026909/43182256-494bc04a-9013-11e8-9c81-fa2db08b4082.png)

actually, **all of those components which haven't been imported by the `other.js` page are lost**.

and when this occurs, you can do nothing to get the styles back, but only by restart `npm run dev`

## Expected behavior
I have tried more UI framework such as 'zent', and got into the same problem. so I think it's not a bug of antd

I hope the styles can work properly, wherever they were imported.

## System information
 - OS: Windows 10
 - Version of Next.js: 6.1.1

**Comment by timneutkens** [comment]
> but I think it's not a bug of example, it's a bug of next.js.

Pretty sure it *is* a bug in the example. As Next.js doesn't handle styles besides styled-jsx, and antd doesn't use styled-jsx.

**Comment by naojamg** [comment]
i think the problem you describe is related with the custom document component, here are two closed issues about that: https://github.com/zeit/next.js/issues/251 and https://github.com/zeit/next.js/issues/1035

**Comment by wslx520** [comment]
@naojamg noop, there is no custom document in `with-ant-design` example

**Comment by wslx520** [comment]
@timneutkens Thank u for your hard work! I **upgraded the next.js and plugin to the lateset canary version**, then this issue has gone. I think this issue has been resolved

**Comment by timneutkens** [comment]
Great, will close this then.

**Comment by qbf75196** [comment]
Hi @wslx520, I have next ver 6.1.1 and next-css ver 0.2.0 but I still have the issue with style disappearing. How did you fix it?

**Comment by wslx520** [comment]
@qbf75196  I updated dependencies to latest `canary` version:

```javascript
"dependencies": {
    "@zeit/next-css": "^0.2.1-canary.1",
    "antd": "^3.3.1",
    "babel-plugin-import": "^1.1.1",
    "next": "^6.1.1-canary.3",
    "react": "^16.0.0",
    "react-dom": "^16.0.0"
  }
```
and no changes in next.config.js:

```javascript
/* eslint-disable */
const withCss = require('@zeit/next-css')

// fix: prevents error when .css files are required by node
if (typeof require !== 'undefined') {
  require.extensions['.css'] = (file) => {}
}

module.exports = withCss()
```

Above code is based on `with-ant-design` example as I said.

may help u
