### ISSUE TITLE
Error styles not cleared, even after a refresh.

### ISSUE THREAD

**Issue by denniscollective** [zeit/next.js#495]
Hey, I'm on the 2.0 beta, after you generate an error, a burgundy background gets applied.

After you fix the error, the burgundy style is still there, below your content. Refreshing doesn't help, but restarting the server makes it go away.

Thanks for next! <3

**Comment by rauchg** [comment]
Can you describe what error exactly you triggered @denniscollective ?

**Comment by denniscollective** [comment]
If I reference a nonexesitent component it renders this backtrace:

after I fix it (change <Headaa> back to <Head>, if I hard reset (#496), I see my content, but on top of a burgundy background.

```
ReferenceError: Headaa is not defined
    at Page.render (/Users/dennis/workspace/jarvo/pages/index.js?entry:30:10)
    at /Users/dennis/workspace/jarvo/node_modules/react-dom/lib/ReactCompositeComponent.js:796:21
    at measureLifeCyclePerf (/Users/dennis/workspace/jarvo/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
    at null.ReactCompositeComponent._renderValidatedComponentWithoutOwnerOrContext (/Users/dennis/workspace/jarvo/node_modules/react-dom/lib/ReactCompositeComponent.js:795:25)
    at null.ReactCompositeComponent._renderValidatedComponent (/Users/dennis/workspace/jarvo/node_modules/react-dom/lib/ReactCompositeComponent.js:822:32)
    at null.ReactCompositeComponent.performInitialMount (/Users/dennis/workspace/jarvo/node_modules/react-dom/lib/ReactCompositeComponent.js:362:30)
    at null.ReactCompositeComponent.mountComponent (/Users/dennis/workspace/jarvo/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.ReactReconciler.mountComponent (/Users/dennis/workspace/jarvo/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at null.ReactCompositeComponent.performInitialMount (/Users/dennis/workspace/jarvo/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at null.ReactCompositeComponent.mountComponent (/Users/dennis/workspace/jarvo/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
```

**Comment by nkzawa** [comment]
This should be fixed on `2.0.0-beta.2`.

**Comment by denniscollective** [comment]
I've upgraded to  2.0.0-beta.2  but am still seeing some issues, they only surface when I refresh while the app is in a broken state, I put more detail on #496
