### ISSUE TITLE
Styles being rendered in duplicate

### ISSUE THREAD

**Issue by ivoreis** [zeit/next.js#501]
Hi,

Running the example, using a custom Document [(with-styled-components)](https://github.com/zeit/next.js/tree/master/examples/with-styled-components) I noticed that the stylesheets are being added in duplicate to the page. 

Apparently flushing the stylesheets like we're doing [here](https://github.com/zeit/next.js/blob/master/examples/with-styled-components/pages/_document.js#L6) avoids this issue but raises a total different one (FOUC).

Any idea why the stylesheets are being added more than once and any tip how to avoid this?

**Comment by nkzawa** [comment]
Basically, styled-component doesn't officially support SSR yet. I'm not sure if we can avoid this.

https://github.com/styled-components/styled-components/issues/124

**Comment by demoneaux** [comment]
Based on my experience, the stylesheets are added more than once only when on dev mode, when hot reloading is enabled. Apart from that, I haven't encountered this issue elsewhere, so this issue isn't that serious, although it can still cause problems.

**Comment by timneutkens** [comment]
@nkzawa I guess this is fixed by #668, might have to update the example.

**Comment by nkzawa** [comment]
@timneutkens it doesn't fix the issue since styles of styled-components are not rendered by `next/head`.

**Comment by timneutkens** [comment]
Styled-components has released a v2 branch under `2.0.0` which is currently in pre-release
try `npm install styled-components@2.0.0-4`

It has better server rendering support. @ivoreis could you try to implement it?
