### ISSUE TITLE
Update to 8.0.4 breaks next build

### ISSUE THREAD

**Issue by johnrackles** [zeit/next.js#6861]
# Bug report

## Describe the bug

After updating to nextjs 8.0.4 `next build` throws the following error:

```
internal/crypto/hash.js:58
    throw new ERR_INVALID_ARG_TYPE('data',
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type number
    at Hash.update (internal/crypto/hash.js:58:11)
```
Downgrading to 8.0.3 fixes that.

## To Reproduce
run `next build`

## Expected behavior
next build runs without problems.

## System information
 - OS: CentOS 7
 - Version of Next.js: 8.0.4

## Additional context

This only happens on CentOS 7 with node v10.15.1, running next build on MacOS gives no problems.

**Comment by dimensi** [comment]
Have same problem
```
internal/crypto/hash.js:53
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'data',
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView
    at Hash.update (internal/crypto/hash.js:53:11)
    at ids.forEach.id (/var/www/digitalhorizon.ru/node_modules/next/dist/build/webpack/plugins/hashed-chunk-ids-plugin.js:24:41)
    at Array.forEach (<anonymous>)
    at compilation.hooks.beforeChunkIds.tap.chunks (/var/www/digitalhorizon.ru/node_modules/next/dist/build/webpack/plugins/hashed-chunk-ids-plugin.js:24:25)
    at SyncHook.eval [as call] (eval at create (/var/www/digitalhorizon.ru/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (/var/www/digitalhorizon.ru/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeTree.callAsync.err (/var/www/digitalhorizon.ru/node_modules/webpack/lib/Compilation.js:1275:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/digitalhorizon.ru/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/var/www/digitalhorizon.ru/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/var/www/digitalhorizon.ru/node_modules/webpack/lib/Compilation.js:1244:27)
    at hooks.make.callAsync.err (/var/www/digitalhorizon.ru/node_modules/webpack/lib/Compiler.js:624:17)
    at _err0 (eval at create (/var/www/digitalhorizon.ru/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:11:1)
    at _addModuleChain (/var/www/digitalhorizon.ru/node_modules/webpack/lib/Compilation.js:1095:12)
    at processModuleDependencies.err (/var/www/digitalhorizon.ru/node_modules/webpack/lib/Compilation.js:1007:9)
    at process._tickCallback (internal/process/next_tick.js:176:11)
```

OS: Ubuntu 16.04.3 LTS
Version of Next.js: 8.0.4

**Comment by Timer** [comment]
Hi! We're unable to reproduce this and will need a reproducable demo to get this fixed. Thanks!

**Comment by tangye1234** [comment]
I reproduce the issue only in one of my server, that is too wired.

**Comment by tangye1234** [comment]
```bash
> Location: "/data/wwwroot/koa-passport/.babelrc"
(node:10286) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type number
    at Hash.update (internal/crypto/hash.js:58:11)
    at ids.forEach.id (/data/wwwroot/koa-passport/node_modules/next/dist/build/webpack/plugins/hashed-chunk-ids-plugin.js:24:41)
    at Array.forEach (<anonymous>)
    at compilation.hooks.beforeChunkIds.tap.chunks (/data/wwwroot/koa-passport/node_modules/next/dist/build/webpack/plugins/hashed-chunk-ids-plugin.js:24:25)
    at SyncHook.eval [as call] (eval at create (/data/wwwroot/koa-passport/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (/data/wwwroot/koa-passport/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeTree.callAsync.err (/data/wwwroot/koa-passport/node_modules/webpack/lib/Compilation.js:1275:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/data/wwwroot/koa-passport/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/data/wwwroot/koa-passport/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/data/wwwroot/koa-passport/node_modules/webpack/lib/Compilation.js:1244:27)
(node:10286) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10286) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 21.49s.
```

**Comment by timneutkens** [comment]
Please provide a reproduction.

**Comment by felixmosh** [comment]
> ```shell
> > Location: "/data/wwwroot/koa-passport/.babelrc"
> (node:10286) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type number
>     at Hash.update (internal/crypto/hash.js:58:11)
>     at ids.forEach.id (/data/wwwroot/koa-passport/node_modules/next/dist/build/webpack/plugins/hashed-chunk-ids-plugin.js:24:41)
>     at Array.forEach (<anonymous>)
>     at compilation.hooks.beforeChunkIds.tap.chunks (/data/wwwroot/koa-passport/node_modules/next/dist/build/webpack/plugins/hashed-chunk-ids-plugin.js:24:25)
>     at SyncHook.eval [as call] (eval at create (/data/wwwroot/koa-passport/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
>     at SyncHook.lazyCompileHook (/data/wwwroot/koa-passport/node_modules/tapable/lib/Hook.js:154:20)
>     at hooks.optimizeTree.callAsync.err (/data/wwwroot/koa-passport/node_modules/webpack/lib/Compilation.js:1275:30)
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (/data/wwwroot/koa-passport/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
>     at AsyncSeriesHook.lazyCompileHook (/data/wwwroot/koa-passport/node_modules/tapable/lib/Hook.js:154:20)
>     at Compilation.seal (/data/wwwroot/koa-passport/node_modules/webpack/lib/Compilation.js:1244:27)
> (node:10286) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:10286) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> Done in 21.49s.
> ```
> 
> # Context
> CentOS 7
> node v10.15.3
> yarn v1.15.2

Same here, locally it passes, on my server (centOS 7) it fails.

**Comment by timneutkens** [comment]
I'd like to point out that saying "same here" won't solve the issue. We need a reproduction to look into this issue and to add tests for it (if applicable).

**Comment by Timer** [comment]
@felixmosh we're unable to help you without someone providing a reproduction.

**Comment by felixmosh** [comment]
> I'd like to point out that saying "same here" won't solve the issue. We need a reproduction to look into this issue and to add tests for it (if applicable).

Seems that is somehow related to the server type, I can't give an access to my server :]

From the error, seems that it is related to *webpack*'s `hashed-chunk-ids-plugin` that provide a wrong type of data to crypt.

**Comment by felixmosh** [comment]
I suspect that this https://github.com/zeit/next.js/blob/canary/packages/next/build/webpack/plugins/hashed-chunk-ids-plugin.ts#L27 casting into `string[]` is not correct.

**Comment by Timer** [comment]
@felixmosh unless someone provides a reproduction there's nothing we can do here to fix it. We don't need access to your server -- just some application source code. We can spin up our own CentOS server. 😄

**Comment by felixmosh** [comment]
@Timer 
Funny response, cause this is just like "solve" the issue, cause If I know  the root cause of the issue, I can make a reproduction repo, and I can PR a fix.
Unfortunately this is not the case, I tried with a simple next app with one page, it not reproduces on my prod server.

**Comment by franklinlugo** [comment]
I solved this issue deleting the old `.next` folder and executing build script again

**Comment by tangye1234** [comment]
> I solved this issue deleting the old `.next` folder and executing the build script again

That is awesome! Thanks.

**Comment by Timer** [comment]
Looks like everyone found a resolution. Please purge your `.next/` folder!

**Comment by edlerd** [comment]
can the next version of next purge the .next folder automatically?

**Comment by threem0126** [comment]
purge the .next folder... It doesn't work for me! 
We have to downgrade to 7.0.3

**Comment by tengfei-blacksketch** [comment]
> Hi! We're unable to reproduce this and will need a reproducable demo to get this fixed. Thanks!

https://codesandbox.io/s/w02r5ppox5

```
yarn build
```

**Comment by pfyod** [comment]
@Timer: I believe that this needs to be reopened. As previously mentioned, https://github.com/zeit/next.js/blob/canary/packages/next/build/webpack/plugins/hashed-chunk-ids-plugin.ts#L27 does not properly convert ids to string. 

https://github.com/zeit/next.js/issues/6861#issuecomment-479138312 <- this fix works.

**Comment by Timer** [comment]
This was fixed in the latest `canary` -- please upgrade.

**Comment by sergodeeva** [comment]
@Timer I installed 8.1.1-canary.19, but still get this issue on CentOS server. 
For now solved it using @felixmosh 's solution:
Changed code in hashed-chunk-ids-plugin.js to`ids.forEach(id => h.update(`${id}`))`

**Comment by hibearpanda** [comment]
@Timer 
I'd like to request this issue to be open as well. I've ran into this issue as well after I installed the react-pdf package. I am using next 8.1.0.

I've tried deleting my build / .next folder as others have suggested, but the error still exists.

@felixmosh 's solution worked for me as well. As suspected / surmised earlier, when I log the ids in the `.forEach` loop, I encounter an id that is not a string, but an integer.

**Comment by dydokamil** [comment]
@hibearpanda same here - does not work after installing react-pdf

**Comment by ahmadalfy** [comment]
I didn’t have a `.next` directory so I removed `build` and it worked

**Comment by Timer** [comment]
Hi! If you're still experiencing this please create a new issue with a clear and concise reproduction. Please note that comments left on closed issues typically go unnoticed. Thank you!
