### ISSUE TITLE
Navigation issue with Browser Back Button Click

### ISSUE THREAD

**Issue by ninjawhocodes** [zeit/next.js#7091]
Issue  :

1. From http://localhost:3000 navigate to http://localhost:3000/p/hello using Link.
2. Refresh the page.
3. Click back button : It goes to http://localhost:3000 but still renders the content of http://localhost:3000/p/hello it is not loading the content of http://localhost:3000.

**I am using "next": "^8.1.0".**

**Comment by MarchWorks** [comment]
@ninjawhocodes I can't reproduce the problem, can you post a reproduction repo and the version of your browser

**Comment by timneutkens** [comment]
Thanks @MarchWorks

**Comment by ninjawhocodes** [comment]
https://github.com/ninjawhocodes/react-with-next

I have upload the code on above repo.

Steps to reproduce the issue :

1. npm install.
2. npm run dev.
3. Once page is up click on "here".
4 . You will be on "http://localhost:3000/p/hello"
5. Do a refresh from browser.
6 Click browser back button.
7. It will go back to "http://localhost:3000" but it will still show the content of  "http://localhost:3000/p/hello".

![image](https://user-images.githubusercontent.com/42357356/56519386-8fc71c00-655f-11e9-9f7a-d6c33629d2d9.png)

![image](https://user-images.githubusercontent.com/42357356/56519584-0a903700-6560-11e9-8c8c-9b3a3f3af211.png)

Aftet Clicking Back 
![image](https://user-images.githubusercontent.com/42357356/56519658-3f9c8980-6560-11e9-8282-ded7fc8bb023.png)

**Comment by ninjawhocodes** [comment]
> @ninjawhocodes I can't reproduce the problem, can you post a reproduction repo and the version of your browser

https://github.com/zeit/next.js/issues/7091#issuecomment-485517546
I have uploaded the code on above and sharing the details in below in fresh comment. Please suggest if this issue can be fixed by doing some workaround.

**Comment by MarchWorks** [comment]
@timneutkens there is an issue caused by importing css files

**Comment by ninjawhocodes** [comment]
> @timneutkens there is an issue caused by importing css files. I will open a new issue with what I found

okay so for time being could you please suggest a workaround ?

**Comment by MarchWorks** [comment]
@ninjawhocodes use styled-jsx https://github.com/zeit/next.js#built-in-css-support

**Comment by MarchWorks** [comment]
@ninjawhocodes personally I will recommend you to use styled-jsx but if you want to use css file then make sure that you are importing one in every page it can be the same or a different one it doesn't matter

**Comment by ninjawhocodes** [comment]
> @ninjawhocodes personally I will recommend you to use styled-jsx but if you want to use css file then make sure that you are importing one in every page it can be the same or a different one it doesn't matter

Yeah, I have to add style.css for each page then only it will work.

**Comment by MarchWorks** [comment]
@ninjawhocodes you should also know that if you import `b.css` in `b.js` and `a.css` in `a.js` and you go from `a.js` page to `b.js` page you will have the style of `a.css` loaded in `b.js` too

**Comment by iMerica** [comment]
New distinct issue that occurs even without a page refresh: https://github.com/zeit/next.js/issues/9989

**Comment by zachwhitedev** [comment]
Every time I hit the back button on mobile my Next.js site loads the page for a second but then the whole page goes blank, and I get the message "An unexpected error occurred."

![Screen Shot 2020-02-29 at 10 59 00 PM](https://user-images.githubusercontent.com/52550132/75621301-2765a580-5b47-11ea-82fa-23d3d0b220a4.png)

Only happens in mobile (on both Chrome and Safari) but not on desktop.

My code:

![Screen Shot 2020-02-29 at 11 01 20 PM](https://user-images.githubusercontent.com/52550132/75621328-6f84c800-5b47-11ea-8c8e-69295cac5f70.png)

**Comment by stikler51** [comment]
@zachwhitedev I have the same problem. Do you find some solution?

**Comment by chiqui3d** [comment]
The same thing happens to me in production and development, the second I return to the home page, I put an error capture:

![Shit Markdown ](https://image.prntscr.com/image/PnKQKyhHTuaIBR1M_GWFbw.png)


I see this is closed, I have to reopen a new issue?

**Comment by chiqui3d** [comment]
I have also added shallow to the Link component, as in this example, and the error still appears:

```
<Link as={`/blog/${post.slug}`} href="/blog/[slug]" shallow={true}>
```

**Comment by collegewap** [comment]
I have a similar issue:

https://github.com/vercel/next.js/issues/9989#issuecomment-663958815

**Comment by JStein92** [comment]
@zachwhitedev Same issue here. Any update on this? It's a pretty huge bug.

**Comment by JStein92** [comment]
@timneutkens Any update on this? This is a pretty massive issue. Is there an open issue to follow here at least?

**Comment by timkindberg** [comment]
I have this issue navigating between two static pages. I have to click back twice.

1. Start on /home
2. Click /work_orders, navigates properly to Work Orders
3. Back Button once, see tab title change to "Home" but page content stays as Work Orders content
4. Back Button again, see URL and page content change back to Home content

We use a mix of:
- CSS-in-JS (via Chakra-UI) 
- CSS Module imports (aka `import styles from './SomeStyles.module.scss'`)
- Global CSS imports for legacy components in _app.js

Not sure how CSS is causing the issue but wanted to share what we do.

**Comment by tomlagier** [comment]
We're seeing this issue too - navigating forward works OK but navigating backwards doesn't work.

Tested with Next version 9.5.1 and 9.5.3

Also using Chakra, as well as global CSS import.

Link:

```
<Link href="/schedule-appointment">{...}</Link>
```

`/schedule-appointment`:

```
import React, { useEffect } from "react";
import { string } from "prop-types";
import { getUserFromCtx } from "../utils/auth";

function Appointment({ email }) {
  // Embed Calendly inline widget
  useEffect(function addCalendly() {
    const head = document.querySelector("head");
    const script = document.createElement("script");
    script.setAttribute(
      "src",
      "https://assets.calendly.com/assets/external/widget.js"
    );
    head.appendChild(script);
  }, []); // second param causes this to only run once

  const calendlyLink = "...";
  return (
    <div>
      <div id="schedule_form">
        <div
          className="calendly-inline-widget"
          data-url={calendlyLink + "?email=" + email}
          style={{ minWidth: "320px", height: "580px" }}
        />
      </div>
    </div>
  );
}

Appointment.propTypes = {
  email: string.isRequired,
};

export async function getServerSideProps(context) {
  const user = await getUserFromCtx(context);

  // TODO: once calendly adds "Extra Guests" prefill,
  // prefill the extra guests field with all the emails
  // associated with a user's Account
  return {
    props: {
      email: user.user.email,
    },
  };
}

export default Appointment;
```

**Comment by BetaPlays3** [comment]
I am having this same issue on some of my pages. For example I navigate from `/search/field` to `/user/dashboard` and then I click back on the browser, the address of the bar is changed but the content remains the same as `/user/dashboard`

**Comment by ijjk** [comment]
Hi, it sounds like some of the follow-up comments here might be related to https://github.com/vercel/next.js/issues/7395 which was resolved in https://github.com/vercel/next.js/pull/16477 and is available in the latest version of Next.js `v9.5.3`

**Comment by Spirik** [comment]
Upgraded to 9.5.3. Still reproduces for me. Hitting browser's back button results in URL in address bar update, but content on the page remains the same.

**Comment by ijjk** [comment]
@Spirik can you provide a repo with a reproduction where this is occurring for you?

**Comment by idoshamun** [comment]
I have the same issue. Tried to update to 9.5.3 but it didn't help.
I don't use shallow links but I do have `getServerSideProps`.

**Comment by Spirik** [comment]
Will try to recreate the issue with clean install, but not sure, when I'll be able to. The only significant difference with my current setup from clean install is that I don't use CSS modules. And occasionally, I use HOCs with `getInitialProps`.

**Comment by aberba** [comment]
@chiqui3d were you able to resolve the back button showing expected error issue? This same problem is killing me here

**Comment by shambu2k** [comment]
> Hi, it sounds like some of the follow-up comments here might be related to #7395 which was resolved in #16477 and is available in the latest version of Next.js `v9.5.3`

You meant the canary version?
I tried that, I still have the same issue

**Comment by chiqui3d** [comment]
@aberba Supposedly it is fixed in the canary version. But I haven't tried it, as what it's doing was for a static website, what I did was to replace the Link component with "a" tag.

**Comment by aberba** [comment]
I don't seem to have any router.push() or history action on the page... This is the error I get for mine...something about **n is not a function**

![WhatsApp Image 2020-09-15 at 1 52 32 PM](https://user-images.githubusercontent.com/8314648/95765912-0569ff00-0ca2-11eb-99be-a1906f8d8385.jpeg)

**Comment by talaikis** [comment]
+1 with 9.5.5

**Comment by ralppppy** [comment]
Still having this issue I've tried 9.5.3-canary.21. I'm also using a hash in my link. I can use normal a tag to fix it but the page reloads, and it doesnt feel like a react website anymore

**Comment by ralppppy** [comment]
Still having this issue I've tried 9.5.3-canary.21. I'm also using a hash in my link. I can use normal a tag to fix it but the page reloads, and it doesnt feel like a react website anymore

**Comment by Mike-Koech** [comment]
>P>>>Treat each variables as secure,& now eliminate instructions,add voice
enabled instructions,For command prompt >>Add voice enabled command,a note
audio route>   it should command all the Servers*/)>>

**Comment by akratzel** [comment]
Facing the same issue. Any updates or solution?

**Comment by conordavidson** [comment]
Still having an issue here. Any updates?

**Comment by aberba** [comment]
The `useEffect` function of mine was has a `return null` which was causing my problem. Removing that fixed my issues. You may just use `return` without a value.  `useEffect` expects only a cancellation function to be returned if any, else nothing else should be returned.

**Comment by cambaughn** [comment]
I'm still experiencing this issue. Forward and back buttons work as long as I don't refresh, but after a refresh on a page with dynamic content, pressing the back button results in the url updating correctly but the page not rendering the correct page.

**Comment by ijjk** [comment]
@cambaughn that sounds related to the page state with dynamic routes, I added a note for this behavior in https://github.com/vercel/next.js/pull/26320 does the note added there help with your case?

**Comment by cambaughn** [comment]
@ijjk That makes sense, but in this case it's not an issue of navigating between the same pages with dynamic routes, it's any page at all, I'm finding.

I finally solved it, and it turned out to be an issue with some code I had to fix scroll restoration on my app.

Here is the code before the fix:
```
  const handleScrollRestoration = () => {
    window.history.scrollRestoration = "manual";

    const cachedScroll = [];

    router.events.on("routeChangeStart", () => {
      cachedScroll.push([window.scrollX, window.scrollY]);
    });

    router.beforePopState(() => {
      if (cachedScroll.length > 0) {
        const [x, y] = cachedScroll.pop();
        setTimeout(() => {
          window.scrollTo(x, y);
        }, 100);

        return true;
      } 
    });
  }
```

The issue was that I didn't have router.beforePopState returning `true` unless it was also performing a scroll restoration. So, when I refreshed the page, it didn't have anything in the cachedScroll array. So, the fix was to add an additional `else` to the function.

```
    router.beforePopState(() => {
      if (cachedScroll.length > 0) {
        const [x, y] = cachedScroll.pop();
        setTimeout(() => {
          window.scrollTo(x, y);
        }, 100);

        return true;
      } else {
        return true;
      }
    });
```

**Comment by atulpe** [comment]
@ayush-pe this seems to be related

**Comment by ImTemporaryHere** [comment]
still have this problem with clicking back after page was  reloaded, just nothing changes.

**Comment by brunobraga95** [comment]
Same here

**Comment by icyJoseph** [comment]
I ran into this issue today, while implementing a pagination solution. Everything worked fine, but navigating back to the starting page index, would show a stale page. 

For example, landing in  http://localhost:3000/t-shirts/?page=1, and then moving to page=2, and page=3, both using `shallow=true`, and then clicking the browser back button until the first entry, would be stuck age page=2.

My page uses `getServerSideProps`, but it receives empty props, when I return the server timestamp and read it inside the page, then things work normally.

```ts
export function getServerSideProps(context: GetServerSidePropsContext) {
    const timestamp = new Date().getTime();

    if (!isValidReq(context)) return {notFound: true};

    return {props: {timestamp}};
}

function ShirtsPage({timestamp}){
// body of page
}

```

Another work around I found, is to force render, when the router change starts. Namely when the options object is `shallow:false`:

```ts
// inside the page component
const force = useReducer((x) => !x, false)[1];

useEffect(() => {
  Router.events.on('routeChangeStart', (_, options) => {
      if (!options.shallow) { force(); }
   });
}, [force]);
```

I guess it has to do with the fact that to navigate to the other pages I use shallow set to true, but the very first page starts navigation with shallow false, which runs `getServerSideProps` and side the input props are the same the page does not render again.

**Comment by anerror404** [comment]
Have been facing this problem for long time. Problem still exists after updating from next js version 9 to the latest. it's a pretty major issue.

**Comment by akratzel** [comment]
> Have been facing this problem for long time. Problem still exists after updating from next js version 9 to the latest. it's a pretty major issue. 
> 
> 

Make sure you're using no third party library that messes with your browsers history. Taking care of a clean history fixed it for me.
The lib that caused the issue for me was snipcart.

**Comment by icyJoseph** [comment]
> Have been facing this problem for long time. Problem still exists after updating from next js version 9 to the latest. it's a pretty major issue.



> > Have been facing this problem for long time. Problem still exists after updating from next js version 9 to the latest. it's a pretty major issue.
> 
> Make sure you're using no third party library that messes with your browsers history. Taking care of a clean history fixed it for me.
> The lib that caused the issue for me was snipcart.

This! I had posted what I thought was a force fix, but after walking away from it for a coffee break, I realized it did nothing, so I began to disconnected other libraries, and to my surprise it was the Service Worker I had. It was capturing .json requests and messing up with the back button. Specifically it was MSW, once I turned it off, things worked swell.

**Comment by douglasjunior** [comment]
> > Have been facing this problem for long time. Problem still exists after updating from next js version 9 to the latest. it's a pretty major issue.
> 
> Make sure you're using no third party library that messes with your browsers history. Taking care of a clean history fixed it for me. The lib that caused the issue for me was snipcart.

We are having this problem when using `react-scroll`, however this is a limitation of NextJS as we use `react-scroll` with `gatsby` and with `react-router` without any problem. 

Did anyone manage to solve it?

**Comment by fudgi** [comment]
i solved my problem by finding that router.replace triggers on every page by mistake
