### ISSUE TITLE
Styled-jsx module not found

### ISSUE THREAD

**Issue by timneutkens** [zeit/next.js#951]
I believe this is related to #926.

All modules get absolute paths except styled-jsx.

For example in `.next/dist/pages/_error.js`.
You can try this with the `custom-server` example by going to a 404 route. `/example` for example.

```
Error: Cannot find module 'styled-jsx/style'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> .next/dist/pages/_error.js:27:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
```

**Comment by timneutkens** [comment]
Found the issue. Creating a PR now.

**Comment by arunoda** [comment]
Okay. Here's what's happening is pretty interesting.
`styled-jsx/babel` add the import statement of `styled-jsx/style`
Since we don't transpile ES2015 modules, `styled-jsx/style` won't get resolved via babel. 
(But it happens earlier)

Let's see what we can do.

**Comment by thetoxicavenger** [comment]
How does one access this fix? Using next 3.0.3 I am still getting this error. Let me know if you need any more info from me.

**Comment by Mensae** [comment]
[Possibly related](https://github.com/zeit/styled-jsx/issues/302)?

**Comment by thetoxicavenger** [comment]
Haha yep found it yesterday! Got it allll working now. Thank you!
